### ISSUE TITLE
Stream callbacks stop firing after a couple of hours

### ISSUE THREAD

**Issue by andreasdc** [koord-live/KoordASIO#11] opened 2024-02-22 00:07 UTC
The same issue as described here https://github.com/dechamps/FlexASIO/issues/217 is in KoordASIO too.
After some time Adobe Audition doesn't detect input and output and it needs to be restarted to have them working again.

**Comment by danryu** [comment] 2024-02-22 05:34
It's not clear from the bug report how the problem manifests exactly.
Are you actively using Adobe Audition at the moment that the issue occurs? And when it occurs, do you lose audio, or does Adobe Audition lose its ASIO configuration suddenly??

As you reported in the FlexASIO issue that this issue happens after a few minutes, which would be easily reproducible and widely reported if it were a general issue, the root cause would appear to be related to a) some aspect of your hardware+software setup or b) some issue within Adobe Audition itself.
This issue has not been reported with any other ASIO host, either in FlexASIO or KoordASIO as far as I'm aware.

**Comment by andreasdc** [comment] 2024-02-22 17:32
I use Adobe Audition for audio mastering in the real time. When it happens there is nothing in the input and output, you need to restart the adobe audition.
It is very easy to reproduce, today it happened after couple hours, chaning buffer size from 512 to 1024 delayed the bug in maybe 1 or 2 days.

**Comment by andreasdc** [comment] 2024-02-27 14:47
I still have this problem.

**Comment by andreasdc** [comment] 2024-03-17 21:47
When using auto convert on FlexASIO it doesn't appear, do you know what's the issue?

**Comment by danryu** [comment] 2024-03-18 07:48
If you mean the FlexASIO option `wasapiAutoConvert` set to true, that is the default which is also used in KoordASIO, so you should see the same behavior between both.
Perhaps you have other options combined in FlexASIO? Please report this to the FlexASIO author as this may be useful information.

**Comment by andreasdc** [comment] 2024-03-18 07:50
No response on FlexASIO, this is the config:
`backend = "Windows WASAPI"
bufferSizeSamples = 64
[input]
device = "Input (SSL 2+ USB Audio Device)"
wasapiExclusiveMode = false
wasapiAutoConvert = true
[output]
device = "Line 1 (Virtual Audio Cable)"
wasapiExclusiveMode = false
wasapiAutoConvert = true
`
I remember that I had this issue with KoordASIO.

**Comment by danryu** [comment] 2024-03-18 08:02
> No response on FlexASIO, this is the config: `backend = "Windows WASAPI" bufferSizeSamples = 64 [input] device = "Input (SSL 2+ USB Audio Device)" wasapiExclusiveMode = false wasapiAutoConvert = true [output] device = "Line 1 (Virtual Audio Cable)" wasapiExclusiveMode = false wasapiAutoConvert = true ` I remember that I had this issue with KoordASIO.

Is this the config with FlexASIO which works for you without errors?
This is identical to the config set by KoordASIO in WASAPI Shared Mode, with one difference: 
KoordASIO sets
`        suggestedLatencySeconds = 0.0` 
but the default is different in FlexASIO.

Could you please confirm whether you have this same bug when you are not using VB-Audio Virtual Audio devices? They are likely to produce a lot of unpredictable behavior.

**Comment by andreasdc** [comment] 2024-03-18 08:11
I think I was only using exclusive mode, with it I have these issues on FlexASIO too.
I tested Virtual Audio Cable and VB-Audio Cable and it's the same.
With this config I don't have such issue, yes.

**Comment by danryu** [comment] 2024-03-18 08:29
I meant try not using virtual audio interfaces, from whichever supplier, in order to narrow down the failure source.

**Comment by andreasdc** [comment] 2024-03-18 08:30
How would you transfer the audio? I get the raw audio, forward it to Adobe Audition, I do mastering there and I get new audio on virtual line.

**Comment by danryu** [comment] 2024-03-18 08:37
I don't know your setup or requirements and cannot advise on that.
I'm just suggesting that you use KoordASIO/FlexASIO with Adobe Audition WITHOUT virtual audio interfaces **in whatever capacity** in order to test which part is failing. That should be easy enough, right?
The thing that stands out, from what you have told myself and the FlexASIO author, is that you are using virtual audio interfaces.

If you cannot confirm that the bug is NOT present when NOT using virtual audio interfaces in your chosen setup, then I will mark this bug as WONTFIX and I suggest you forward your bug report to the authors of your chosen virtual audio interfaces.

**Comment by andreasdc** [comment] 2024-03-18 08:40
I don't know how would I test it without the virtual audio, but I found that with autoconvert option this issue doesn't appear.

**Comment by danryu** [comment] 2024-03-18 08:43
Use Adobe Audition to record and process some audio with FlexASIO/KoordASIO, just using your physical interface.

I don't know how to explain it any simpler.

**Comment by andreasdc** [comment] 2024-03-18 08:44
That is some way, but that would need probably couple hours of recording. The autoconvert option making that doesn't help anything?

**Comment by danryu** [comment] 2024-03-18 08:49
> That is some way, but that would need probably couple hours of recording. 

That's what is required if you want to confirm the source of a bug.

> The autoconvert option making that doesn't help anything?

I already addressed that in comments above.

As this issue appears to be an issue with user's virtual audio setup, and no confirmation of any bad behavior from KoordASIO, I'm closing this issue.

**Closed as completed by danryu** 2024-03-18 08:49 UTC

**Comment by andreasdc** [comment] 2024-03-18 12:46
It happened without virtual line.

**Comment by andreasdc** [comment] 2024-03-18 18:51
@danryu

**Comment by danryu** [comment] 2024-03-19 06:13
In order for me to have any chance of diagnosing this, I need to have a complete issue reproduction procedure.

Please describe in detail a procedure that will reliably reproduce this issue, without paid or trial software.

Otherwise this issue will remain closed, as I can't confirm the existence of the bug.

**Comment by andreasdc** [comment] 2024-03-20 00:49
All right. I can only say when using Adobe Audition, they have free 7 days trial. It happens with latest or older version. 
1. Open the Audition and create a multitrack session. File -> New -> Multitrack session.
2. Click R and I on the Track 1.
3. Click on the input on the Track and go to Audio hardware (or Edit -> Preferences -> Audio hardware).
4. Pick Device class ASIO
5. Pick device as KoordASIO.
6. Pick any input and output device, set mode to exclusive (shared doesn't create this issue).
7. Set the buffer to small amount like 32-1024.
8. Close the KoordASIO gui and audio hardware options. 
9. Set input and output on the Track 1.
10. After couple hours your sound won't be played.
11. I use some effects on the track, they don't have the impact on it as I believe, but I can check it too.

Let me know if I can help in anyway.

**Comment by andreasdc** [comment] 2024-03-20 19:26
How do you want to do it without paid or trial software? I can test it in the audacity, but I don't feel like you will help.

**Comment by danryu** [comment] 2024-03-23 06:26
It would be very helpful if you could reproduce this issue with freely-available software (I don't think standard Audacity has ASIO support though).

You have to appreciate the nature of contributions to open-source projects like this. Developers like myself are only able to devote small amounts of spare time, as and when it arises, in order to progress the project.
If there are issues being reported, it's usually expected that the bug reporter will do the necessary work in order to provide the developer with all the information necessary to work on it.

As an open-source developer, being asked to reproduce and fix bugs in inter-operation with arbitrary closed-source programs is intensely difficult. In this particular case, you're asking me to devote a 7-day period in which a trial version will be valid, and commit to being able to do all diagnostics, testing and development in that window in order to fix a problem that only 1 person has reported, and only then with a single piece of closed-source software.

Please adjust your expectations accordingly, and provide a reproduction procedure with non-paid, non-trial software.
You may wish to explain your individual use-case as well, as I still don't know what you are attempting or why virtual audio devices were necessary to achieve what you're trying to achieve.

**Comment by andreasdc** [comment] 2024-03-23 08:14
You wanted a way to reproduce it, right? I described the issue for you and I can fully help with testing. I don't see ASIO in Audacity, so I don't know how I can test it.

**Comment by danryu** [comment] 2024-03-23 10:31
> You wanted a way to reproduce it, right? 

With a freely-available, non-trial-limited ASIO-capable DAW, yes.
Why? Because:
- I need evidence that this is reproducible with more than one ASIO host (and a commercial one at that)
- I may need to have a longer diagnostic window than the trial limitation offers (and I don't want to waste effort)

> I don't see ASIO in Audacity, so I don't know how I can test it.

So use a DAW which is freely-available, non-trial-limited that does have ASIO support. A quick Google search shows that SoundBridge and Podium Free are probably good options.

**Comment by andreasdc** [comment] 2024-03-23 10:32
Ok so you want to reproduce it by yourself? But you know it will appear moslty after couple hours. I can try with DAW if you really want, but what then? Do you really think it audition's fault?
